"""add_mail

Revision ID: 1a0d81bd0eb8
Revises: e044fe0f7a60
Create Date: 2025-11-21 14:49:24.659374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a0d81bd0eb8'
down_revision: Union[str, Sequence[str], None] = 'e044fe0f7a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('previous_mail_id', sa.Uuid(), nullable=True),
    sa.Column('written_at', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.JSON(), nullable=True),
    sa.Column('to_recipients', sa.JSON(), nullable=True),
    sa.Column('cc_recipients', sa.JSON(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['previous_mail_id'], ['mail.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail')
    # ### end Alembic commands ###
